# Generated by Django 5.0.6 on 2024-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
