# Generated by Django 5.0.6 on 2024-05-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_city_created_at_city_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebookLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='instagramLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedinLink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitterLink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
