# Generated by Django 5.0.6 on 2024-06-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
