# Generated by Django 5.0.6 on 2024-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('facebookLink', models.URLField(blank=True, null=True)),
                ('instagramLink', models.URLField(blank=True, null=True)),
                ('twitterLink', models.URLField(blank=True, null=True)),
                ('youtubeLink', models.URLField(blank=True, null=True)),
                ('linkedinLink', models.URLField(blank=True, null=True)),
                ('addressLine1', models.TextField(blank=True, null=True)),
                ('addressLine2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('googleMapIframeLink', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
