# Generated by Django 5.0.6 on 2024-06-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyStatus',
            field=models.CharField(choices=[('SOLD', 'SOLD'), ('FINISHED', 'FINISHED'), ('UNDER_CONSTRUCTION', 'UNDER_CONSTRUCTION'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='landmarkCoordinates',
            field=models.CharField(blank=True, help_text="format: Latitude, Longitude , eg:-25.290747656764527, 23.480395215646162 (to get this right click on the map and select')", max_length=255, null=True),
        ),
    ]
