# Generated by Django 5.0.6 on 2024-06-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_property_propertystatus_and_more'),
        ('app', '0015_statistic_image'),
    ]

    operations = [
    ]
