# Generated by Django 5.0.6 on 2024-06-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cityCoordinates',
            field=models.CharField(blank=True, default='-25.290747656764527, 23.480395215646162', help_text="coordinate of center of city, format: Latitude, Longitude , eg:-25.290747656764527, 23.480395215646162 (to get this right click on the map and select ')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='mapZoom',
            field=models.IntegerField(blank=True, default=12, help_text='Map zoom level for city (ideally between 5 to 20) (default 12)', null=True),
        ),
    ]
