# Generated by Django 5.0.6 on 2024-06-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_property_directions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='directions',
        ),
        migrations.AddField(
            model_name='property',
            name='locationCoordinates',
            field=models.CharField(blank=True, help_text="format: Latitude, Longitude , eg:-25.290747656764527, 23.480395215646162 (to get this right click on the map and select')", max_length=255, null=True),
        ),
    ]
