# Generated by Django 5.0.6 on 2024-06-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('to_show', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('image', models.ManyToManyField(blank=True, related_name='gallery_image', to='app.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
