# Generated by Django 5.0.6 on 2024-06-19 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='images',
        ),
    ]
