# Generated by Django 4.2.13 on 2024-06-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
