# Generated by Django 5.0.6 on 2024-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_contact_message_name_message_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='message',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
